import Head from "next/head";
import Image from "next/image";
import { Button, Col, Row } from "react-bootstrap";
import styles from "../styles/Home.module.css";

export default function Home() {
  const logo = require("./../assets/img/logo/nextdash.png");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.png" />
      </Head>

      <div className="container-scroller">
        <div className="container-fluid page-body-wrapper full-page-wrapper">
          <div className="content-wrapper d-flex align-items-center auth px-0">
            <Row className="w-100 mx-0">
              <Col lg={4} className="mx-auto">
                <div className="auth-form-light text-left py-5 px-4 px-sm-5">
                  <div className="brand-logo">
                    <Image src={logo} alt="logo" width={200} height={50} />
                  </div>
                  <h4>Olá! Vamos começar</h4>
                  <h6 className="font-weight-light">
                    Realize o login para continuar.
                  </h6>
                  <form className="pt-3">
                    <div className="form-group">
                      <input
                        type="text"
                        className="form-control form-control-lg"
                        id="usuario"
                        placeholder="Usuário"
                      />
                    </div>
                    <div className="form-group">
                      <input
                        type="password"
                        className="form-control form-control-lg"
                        id="password"
                        placeholder="Senha"
                      />
                    </div>
                    <div className="mt-3">
                      <a
                        className="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn"
                        href="#Login"
                      >
                        Login
                      </a>
                    </div>
                    <div className="my-2 d-flex justify-content-between align-items-center">
                      <a href="#" className="auth-link text-black">
                        Esquece a senha?
                      </a>
                    </div>
                    <div className="mb-2">
                      <Button
                        type="button"
                        className="btn-block btn-facebook auth-form-btn"
                        variant=""
                      >
                        <i className="ti-facebook me-2"></i>Conectar pelo
                        facebook
                      </Button>
                    </div>
                    <div className="text-center mt-4 font-weight-light">
                      Não possui uma conta?{" "}
                      <a href="register.html" className="text-primary">
                        Criar
                      </a>
                    </div>
                  </form>
                </div>
              </Col>
            </Row>
          </div>
        </div>
      </div>
    </div>
  );
}
